
services:
  order-db:
    image: postgres

  basket-db:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog-db:
    image: mongo:4.4

volumes:
  postgres_data:
  mongo_data:
