spring:
  application:
    name: catalog-service
  data:
    mongodb:
      username: admin
      password: admin
      authentication-database: admin
      port: 27017
      additional-hosts: localhost
      database: catalog

server:
  port: 3002