spring:
  application:
    name: basket-service
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 15000
      client-type: lettuce
  grpc:
    client:
      basket-service:
        address: static://localhost:9090
        negotiation-type: plaintext
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
server:
  port: 3000