spring:
  application:
    name: ordering-api
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    password: password
    username: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2.0
server:
  port: 3001

email:
  from: fredrickamoako@gmail.com
  api-key:
  from-name: freddie

logging:
  level:
    org:
      springframework:
        beans: DEBUG
        context.annotation: TRACE
        boot.autoconfigure: DEBUG

debug: true

trace: true